### ISSUE TITLE
Hitting unreachable in `DiscoveryManager`

### ISSUE THREAD

**Issue by RCasatta** [Blockstream/electrs#129]
[This](https://github.com/Blockstream/electrs/blob/dca8c5996a4b69e1544a481e1809d0deaf54c771/src/electrum/discovery.rs#L310) line is hit 

![image](https://github.com/user-attachments/assets/3a335376-30dd-45f7-8dfc-cea606637721)

At the moment it's not clear to me:

- why the entry is supposed to be always found and the reason of unreachable
- why electrs crash since the panic should be inside a spawned thread

**Comment by philippem** [comment]
@shesek any idea?

**Comment by shesek** [comment]
> why the entry is supposed to be always found

It should be impossible to have a job in the `queue` that was healthy on the last check without a corresponding entry in the `healthy` set. I went over the code again and am still unsure how this could happen.

Are you hitting this consistently? Any reproduction steps?

> and the reason of unreachable

I generally prefer to use `unreachable`s for impossible/inconsistent states, but changing this to a `warn` would be ok too.

> why electrs crash since the panic should be inside a spawned thread

I'm not sure, looking into this.

**Comment by shesek** [comment]
> > why electrs crash since the panic should be inside a spawned thread
> I'm not sure, looking into this.

I was unable to reproduce this with an explicit `panic!()` in the discovery thread. It logs the panic but keeps running:

```
DEBUG updating synced tip to 0x7ad0aabebdfa25df11c4cb73aeefcfdca680fce9050fe72c079c1d118201829e
TRACE mempool is synced
thread 'discovery-jobs' panicked at src/electrum/discovery.rs:236:9:
run_health_check
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
TRACE mempool is synced
```
